### ISSUE TITLE
support able to compile into SDL 1.2

### ISSUE THREAD

**Issue by mckaygerhard** [kallisti5/huexpress#14]
i see that this are to port hugo to modern systems, but performance of the SDL 2 in my eeepc's are very poor, also in my only mini-laptop SDL 1.2 realted apps runs more faster due SDL 1 sue less cpu cycles (obviously less feaures)

so a chance to be able to **compile huexpress in sdl 1 will be great for this (now in many countries) more cheap computers, due the current economic decease**

**Comment by kallisti5** [comment]
For SDL 1.x support, i'd recommend trying the older hugo.  SDL is really only used for controls and setting up OpenGL.  huexpress uses OpenGL for video scaling, while hugo uses 2d SDL drawing. (that is likely what is causing the performance differences)

**Comment by mckaygerhard** [comment]
that performance differences are stupid, why i need a powered 4 cores machine to emulated a stupid 12MHz old videogame?

i want to use it in a older pc, not in a modern!
